<? $this->partial('partials/top.phtml') ?>

<h1>Clipboard</h1>



<ol id="clipboard">
<? foreach ($this->clipboard as $photo): ?>
	<li>
		<img data-id="<?= $photo['id'] ?>" src="<?= $photo['sizes'][count($photo['sizes']) - 1]['source'] /*$this->flickrImageUrl($photo, $photo['id'], 'b')*/ ?>" alt="">
	</li>
<? endforeach ?>
</ol>



<script>
$('#clipboard li').prepend($('<a>', {href: 'javascript:;'}).addClass('delete').text('X').click(function () {
	var $this = $(this);
	$.post('clipboard/toggle', { photo: clipboard[$this.next('img').data('id')] }, function (r) {
		clipboard = r.clipboard;
		clipboardChanged();
		$this.parent().fadeOut();
		
	});
}));
</script>


<? $this->partial('partials/bottom.phtml') ?>